
export const STORE_ORDER_PRODUCT = 'STORE_ORDER_PRODUCT';

export const ORDER_PLACE_REQUEST = "ORDER_PLACE_REQUEST";
export const ORDER_PLACE_SUCCESS = "ORDER_PLACE_SUCCESS";
export const ORDER_PLACE_FAIL = "ORDER_PLACE_FAIL";

export const GET_ALLORDERS_REQUEST = "GET_ALLORDERS_REQUEST";
export const GET_ALLORDERS_SUCCESS = "GET_ALLORDERS_SUCCESS";
export const GET_ALLORDERS_FAIL = "GET_ALLORDERS_FAIL";

export const GET_ORDERDETAILS_REQUEST = "GET_ORDERDETAILS_REQUEST";
export const GET_ORDERDETAILS_SUCCESS = "GET_ORDERDETAILS_SUCCESS";
export const GET_ORDERDETAILS_FAIL = "GET_ORDERDETAILS_FAIL";

export const GET_REVIEWRATING_REQUEST = "GET_REVIEWRATING_REQUEST";
export const GET_REVIEWRATING_SUCCESS = "GET_REVIEWRATING_SUCCESS";
export const GET_REVIEWRATING_FAIL = "GET_REVIEWRATING_FAIL";

export const ADD_REVIEWRATING_REQUEST = "ADD_REVIEWRATING_REQUEST";
export const ADD_REVIEWRATING_SUCCESS = "ADD_REVIEWRATING_SUCCESS";
export const ADD_REVIEWRATING_FAIL = "ADD_REVIEWRATING_FAIL";

export const EDIT_REVIEWRATING_REQUEST = "EDIT_REVIEWRATING_REQUEST";
export const EDIT_REVIEWRATING_SUCCESS = "EDIT_REVIEWRATING_SUCCESS";
export const EDIT_REVIEWRATING_FAIL = "EDIT_REVIEWRATING_FAIL";

export const DELETE_REVIEWRATING_SUCCESS = "DELETE_REVIEWRATING_SUCCESS";
export const DELETE_REVIEWRATING_FAIL = "DELETE_REVIEWRATING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";