
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS";
export const SEARCH_PRODUCTS_FAIL = "SEARCH_PRODUCTS_FAIL";

export const CATEGORY_PRODUCTS_REQUEST = "CATEGORY_PRODUCTS_REQUEST";
export const CATEGORY_PRODUCTS_SUCCESS = "CATEGORY_PRODUCTS_SUCCESS";
export const CATEGORY_PRODUCTS_FAIL = "CATEGORY_PRODUCTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"
