
export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const GET_SELLER_PRODUCT_REQUEST = "GET_SELLER_PRODUCT_REQUEST";
export const GET_SELLER_PRODUCT_SUCCESS = "GET_SELLER_PRODUCT_SUCCESS";
export const GET_SELLER_PRODUCT_FAIL = "GET_SELLER_PRODUCT_FAIL";

export const EDIT_SELLER_PRODUCT_REQUEST = "EDIT_SELLER_PRODUCT_REQUEST";
export const EDIT_SELLER_PRODUCT_SUCCESS = "EDIT_SELLER_PRODUCT_SUCCESS";
export const EDIT_SELLER_PRODUCT_FAIL = "EDIT_SELLER_PRODUCT_FAIL";

export const DELETE_SELLER_PRODUCT_REQUEST = "DELETE_SELLER_PRODUCT_REQUEST";
export const DELETE_SELLER_PRODUCT_SUCCESS = "DELETE_SELLER_PRODUCT_SUCCESS";
export const DELETE_SELLER_PRODUCT_FAIL = "DELETE_SELLER_PRODUCT_FAIL";

export const GET_SELLER_PRODUCTS_REQUEST = "GET_SELLER_PRODUCTS_REQUEST";
export const GET_SELLER_PRODUCTS_SUCCESS = "GET_SELLER_PRODUCTS_SUCCESS";
export const GET_SELLER_PRODUCTS_FAIL = "GET_SELLER_PRODUCTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";