
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";

export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT_SUCCESS";
export const DELETE_USER_ACCOUNT_FAIL = "DELETE_USER_ACCOUNT_FAIL";

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAIL = "ADD_CART_FAIL";

export const SAVED_FOR_LATER_REQUEST = "SAVED_FOR_LATER_REQUEST";
export const SAVED_FOR_LATER_SUCCESS = "SAVED_FOR_LATER_SUCCESS";
export const SAVED_FOR_LATER_FAIL = "SAVED_FOR_LATER_FAIL";

export const UPDATE_CART_QTY_REQUEST = "UPDATE_CART_QTY_REQUEST";
export const UPDATE_CART_QTY_SUCCESS = "UPDATE_CART_QTY_SUCCESS";
export const UPDATE_CART_QTY_FAIL = "UPDATE_CART_QTY_FAIL";

export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";

export const REMOVE_SAVED_ITEM_SUCCESS = "REMOVE_SAVED_ITEM_SUCCESS";
export const REMOVE_SAVED_ITEM_FAIL = "REMOVE_SAVED_ITEM_FAIL";

export const TOGGLE_WISHLIST_REQUEST = "TOGGLE_WISHLIST_REQUEST";
export const TOGGLE_WISHLIST_SUCCESS = "TOGGLE_WISHLIST_SUCCESS";
export const TOGGLE_WISHLIST_FAIL = "TOGGLE_WISHLIST_FAIL";

export const ADD_NEW_ADDRESS_REQUEST = "ADD_NEW_ADDRESS_REQUEST";
export const ADD_NEW_ADDRESS_SUCCESS = "ADD_NEW_ADDRESS_SUCCESS";
export const ADD_NEW_ADDRESS_FAIL = "ADD_NEW_ADDRESS_FAIL";

export const EDIT_ADDRESS_REQUEST = "EDIT_ADDRESS_REQUEST";
export const EDIT_ADDRESS_SUCCESS = "EDIT_ADDRESS_SUCCESS";
export const EDIT_ADDRESS_FAIL = "EDIT_ADDRESS_FAIL";

export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";