const mongoose = require("mongoose");

const sellerId = new mongoose.Types.ObjectId("689094d8112e65d98becbe6d");;

module.exports = [
  {
    key: "sofa-essentials",
    title: "Modern Corner Sofa",
    description: "Comfortable L-shaped corner sofa with soft cushions and a durable fabric finish. Perfect for living rooms and family spaces.",
    highlights: ["L-shaped", "Stain resistant fabric", "Solid wood frame", "Removable cushions"],
    brand: "Bharat Lifestyle",
    category: "Home&Furniture",
    price: 9999,
    discountedPrice: 7499,
    discountPercent: 25,
    stock: 50,
    localImageFile: "slide1.png",
    isTrending: true
  },
  {
    key: "tcl-4k-tv",
    title: "TCL 43\" 4K Smart TV",
    description: "43-inch 4K UHD Smart LED TV with HDR support, built-in apps and immersive picture quality. Great for living room entertainment.",
    highlights: ["4K UHD", "HDR", "Smart TV (apps)", "Slim bezels"],
    brand: "TCL",
    category: "TVs&Appliances",
    price: 24999,
    discountedPrice: 17249,
    discountPercent: 31,
    stock: 35,
    localImageFile: "slide2.png",
    isTrending: false
  },
  {
    key: "wooden-bed",
    title: "Platform Storage Bed",
    description: "Solid-wood platform bed with integrated storage, comfortable slats and modern design. Available in multiple finishes.",
    highlights: ["Under-bed storage", "Solid wood", "Easy assembly", "King/Queen sizes"],
    brand: "Wooden Street",
    category: "Home&Furniture",
    price: 12999,
    discountedPrice: 8999,
    discountPercent: 31,
    stock: 25,
    localImageFile: "slide3.png",
    isTrending: false
  },
  {
    key: "oppo-reno14",
    title: "OPPO Reno14 5G",
    description: "Flagship one-piece sculpted glass phone with powerful camera, long battery and fast performance.",
    highlights: ["5G", "High-res camera", "Fast charging", "Sculpted glass design"],
    brand: "OPPO",
    category: "Mobiles&Tablets",
    price: 49999,
    discountedPrice: 37999,
    discountPercent: 24,
    stock: 120,
    localImageFile: "slide4.png",
    isTrending: true
  },
  {
    key: "samsung-galaxy-f06",
    title: "Samsung Galaxy F06 5G",
    description: "Affordable 5G smartphone offering reliable performance and long battery life. Ideal for everyday use.",
    highlights: ["5G bands", "Long battery", "Dual SIM", "Value for money"],
    brand: "Samsung",
    category: "Mobiles&Tablets",
    price: 12999,
    discountedPrice: 7999,
    discountPercent: 38,
    stock: 200,
    localImageFile: "slide5.png",
    isTrending: false
  }
];


// exports.productsData = [
//   {
//     title: "Samsung Galaxy S23 Ultra",
//     description: "6.8-inch AMOLED Display, 200 MP Camera, Snapdragon 8 Gen 2",
//     highlights: [
//       "200 MP Quad Camera",
//       "5000 mAh Battery",
//       "S Pen included",
//       "12 GB RAM | 256 GB Storage"
//     ],
//     brand: "Samsung",
//     category: "Mobiles&Tablets",
//     price: 124999,
//     discountedPrice: 109999,
//     discountPercent: 12,
//     stock: 30,
//     images: [],
//     seller: sellerId,
//     ratings: 4.6,
//     numOfReviews: 1543,
//     isTrending: true
//   },
//   {
//     title: "boAt Rockerz 255 Pro+",
//     description: "Wireless Bluetooth Neckband with Fast Charging",
//     highlights: [
//       "Up to 60 Hours Playtime",
//       "IPX7 Water Resistance",
//       "ASAP Charge – 10 mins = 10 hrs"
//     ],
//     brand: "boAt",
//     category: "Electronics",
//     price: 2999,
//     discountedPrice: 1299,
//     discountPercent: 56,
//     stock: 200,
//     images: [],
//     seller: sellerId,
//     ratings: 4.2,
//     numOfReviews: 891,
//     isTrending: false
//   },
//   {
//     title: "Apple iPad 10th Generation",
//     description: "10.9-inch Wi-Fi Tablet (64 GB, Silver)",
//     highlights: [
//       "A14 Bionic chip",
//       "All-day battery life",
//       "iPadOS with multitasking"
//     ],
//     brand: "Apple",
//     category: "Mobiles&Tablets",
//     price: 44999,
//     discountedPrice: 40999,
//     discountPercent: 9,
//     stock: 15,
//     images: [],
//     seller: sellerId,
//     ratings: 4.8,
//     numOfReviews: 1221,
//     isTrending: true
//   },
//   {
//     title: "Havells Instanio 3 L Geyser",
//     description: "Instant Water Heater with LED Indicator",
//     highlights: ["Fire-retardant cord", "ISI Certified", "High-rise friendly"],
//     brand: "Havells",
//     category: "Home&Furniture",
//     price: 4599,
//     discountedPrice: 3499,
//     discountPercent: 24,
//     stock: 40,
//     images: [],
//     seller: sellerId,
//     ratings: 4.1,
//     numOfReviews: 207,
//     isTrending: false
//   },
//   {
//     title: "Philips Trimmer BT3221",
//     description: "Beard Trimmer with 90 mins Runtime, Cordless",
//     highlights: ["Titanium blades", "Charge indicator", "20 length settings"],
//     brand: "Philips",
//     category: "Electronics",
//     price: 2295,
//     discountedPrice: 1795,
//     discountPercent: 22,
//     stock: 60,
//     images: [],
//     seller: sellerId,
//     ratings: 4.2,
//     numOfReviews: 948,
//     isTrending: false
//   },
//   {
//     title: "Nestlé Everyday Dairy Whitener 1 kg",
//     description: "Milk Powder for Tea & Coffee",
//     highlights: ["Great taste & texture", "Shelf stable"],
//     brand: "Nestlé",
//     category: "Grocery",
//     price: 599,
//     discountedPrice: 520,
//     discountPercent: 13,
//     stock: 100,
//     images: [],
//     seller: sellerId,
//     ratings: 4.3,
//     numOfReviews: 421,
//     isTrending: false
//   },
//   {
//     title: "Men's Cotton Solid Shirt",
//     description: "Slim Fit Pure Cotton Casual Shirt",
//     highlights: ["Breathable cotton", "7 colors", "Machine washable"],
//     brand: "Roadster",
//     category: "Fashion",
//     price: 1499,
//     discountedPrice: 749,
//     discountPercent: 50,
//     stock: 50,
//     images: [],
//     seller: sellerId,
//     ratings: 4.0,
//     numOfReviews: 317,
//     isTrending: true
//   },
//   {
//     title: "Realme Smart TV 43\"",
//     description: "Full HD Android TV with Dolby Audio",
//     highlights: ["Chromecast built-in", "Google Assistant", "24 W Quad Speakers"],
//     brand: "Realme",
//     category: "TVs&Appliances",
//     price: 28999,
//     discountedPrice: 23999,
//     discountPercent: 17,
//     stock: 22,
//     images: [],
//     seller: sellerId,
//     ratings: 4.4,
//     numOfReviews: 803,
//     isTrending: true
//   },
//   {
//     title: "Mamaearth Onion Hair Oil 250 ml",
//     description: "Reduces Hair Fall, Promotes Growth",
//     highlights: ["Paraben-silicone free", "Natural ingredients"],
//     brand: "Mamaearth",
//     category: "Beauty,Food&More",
//     price: 599,
//     discountedPrice: 499,
//     discountPercent: 17,
//     stock: 120,
//     images: [],
//     seller: sellerId,
//     ratings: 4.5,
//     numOfReviews: 378,
//     isTrending: false
//   },
//   {
//     title: "Personalized 11oz Ceramic Mug",
//     description: "Microwave & Dishwasher Safe",
//     highlights: ["Customizable text/photo", "Bright print"],
//     brand: "Printo",
//     category: "Others",
//     price: 399,
//     discountedPrice: 249,
//     discountPercent: 38,
//     stock: 80,
//     images: [],
//     seller: sellerId,
//     ratings: 4.7,
//     numOfReviews: 120,
//     isTrending: false
//   }
// ];
